# Generated by Django 2.0 on 2018-01-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='identity_number',
            field=models.IntegerField(max_length=30, unique=True),
        ),
    ]
