# Generated by Django 2.0 on 2018-01-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180102_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='user',
        ),
    ]
