# Generated by Django 2.0 on 2018-03-22 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180322_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='kelas',
        ),
        migrations.AddField(
            model_name='student',
            name='kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Kelas'),
        ),
    ]
