# Generated by Django 2.0 on 2018-03-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180322_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='class_name',
            field=models.CharField(max_length=20),
        ),
    ]
