# Generated by Django 2.0.5 on 2018-05-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_grade_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade_name',
        ),
        migrations.AddField(
            model_name='grade',
            name='study_year',
            field=models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four'), ('five', 'Five')], default='one', max_length=5),
        ),
        migrations.AddField(
            model_name='grade',
            name='term',
            field=models.CharField(default='', max_length=5),
        ),
    ]
