# Generated by Django 2.0.5 on 2018-05-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180526_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='term',
            field=models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three')], default='one', max_length=5),
        ),
    ]
