# Generated by Django 2.0 on 2018-03-22 08:49

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core', '0010_auto_20180322_0813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kelas',
            new_name='Classroom',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='kelas',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='list',
            new_name='lists',
        ),
    ]
