# Generated by Django 2.0.5 on 2018-05-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180526_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='english',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='grade',
            name='geography',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='grade',
            name='malay',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='grade',
            name='mathematics',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='grade',
            name='science',
            field=models.CharField(default='', max_length=5),
        ),
    ]
