# Generated by Django 2.0 on 2018-03-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180322_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='behavior',
            new_name='behaviour',
        ),
    ]
