# Generated by Django 2.0 on 2018-03-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180322_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='behaviour',
            new_name='behavior',
        ),
    ]
