# Generated by Django 2.0 on 2018-03-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core', '0015_auto_20180322_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classroom_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_classroom_name', to='core.Classroom'),
        ),
        migrations.AlterModelTable(
            name='classroom',
            table='classrooms',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
