# Generated by Django 2.0 on 2018-03-22 14:47

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core', '0016_auto_20180322_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom_name',
        ),
        migrations.AlterModelTable(
            name='classroom',
            table=None,
        ),
    ]
