# Generated by Django 2.0.5 on 2018-05-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180325_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='students',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendees',
            field=models.ForeignKey(default='', on_delete='SET_NULL', to='core.Student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='classroom_students', to='core.Student'),
        ),
    ]
